import {createTheme} from '@fluentui/react';

export const thrThemeDark = createTheme({
	palette: {
		themePrimary: '#e67b1e',
		themeLighterAlt: '#fef9f5',
		themeLighter: '#fbe8d8',
		themeLight: '#f7d5b7',
		themeTertiary: '#f0ad73',
		themeSecondary: '#e98a37',
		themeDarkAlt: '#cf6f1b',
		themeDark: '#ae5d17',
		themeDarker: '#814511',
		neutralLighterAlt: '#2d2d2d',
		neutralLighter: '#2c2c2c',
		neutralLight: '#2a2a2a',
		neutralQuaternaryAlt: '#272727',
		neutralQuaternary: '#252525',
		neutralTertiaryAlt: '#242424',
		neutralTertiary: '#f1f1f1',
		neutralSecondary: '#f4f4f4',
		neutralPrimaryAlt: '#f6f6f6',
		neutralPrimary: '#ebebeb',
		neutralDark: '#fafafa',
		black: '#fdfdfd',
		white: '#2e2e2e',
	},
});

export const thrThemeLight = createTheme({
	palette: {
		themePrimary: '#e67b1e',
		themeLighterAlt: '#fef9f5',
		themeLighter: '#fbe8d8',
		themeLight: '#f7d5b7',
		themeTertiary: '#f0ad73',
		themeSecondary: '#e98a37',
		themeDarkAlt: '#cf6f1b',
		themeDark: '#ae5d17',
		themeDarker: '#814511',
		neutralLighterAlt: '#eeeeee',
		neutralLighter: '#eaeaea',
		neutralLight: '#e1e1e1',
		neutralQuaternaryAlt: '#d1d1d1',
		neutralQuaternary: '#c8c8c8',
		neutralTertiaryAlt: '#c0c0c0',
		neutralTertiary: '#101010',
		neutralSecondary: '#151515',
		neutralPrimaryAlt: '#1a1a1a',
		neutralPrimary: '#2e2e2e',
		neutralDark: '#242424',
		black: '#292929',
		white: '#f5f5f5',
	},
});
