name: 'Install dependencies'
description: 'Checks out the repository, installs and caches node modules'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: node_modules cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn global add lerna
        yarn lerna bootstrap
        yarn run thx check-git-status

    - name: Check dependencies
      shell: bash
      run: |
        yarn deps -v
