name: 'Build code'
description: 'Runs the build'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: node_modules cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Run build
      shell: bash
      run: |
        yarn build -v

    - name: Build cache
      uses: actions/cache@v2
      id: cache-build
      with:
        path: |
          */*/dist
        key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock', '**/src/**', '*.json', '*.mjs', '*.js', '*.cjs') }}
