name: 'Build code'
description: 'Runs the build'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: node_modules cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
          !node_modules/.cache/nx
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Run build
      shell: bash
      run: |
        yarn build -v

    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        retention-days: 1
        path: |
          **/dist
          !node_modules/**
