name: 'Lint code'
description: 'Checks linting'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: node_modules cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Run linting
      shell: bash
      run: |
        yarn lint -v
