import type {TaskConfig} from '../types';
import {TaskUserType} from '../types';

export const offboardingConfig: TaskConfig = {
	id: 'offboarding',
	title: 'Offboarding',
	completionMessage: 'Your offboarding is complete!',
	phases: {
		I: 'Initiation',
		II: 'Closure',
		III: 'Final Steps',
	},
	steps: [
		{
			id: 'INITIATE_OFFBOARDING',
			label: 'Initiate Offboarding',
			phase: 'I',
			dependsOn: [],
			outputs: ['offboarding_initiated'],
			isDecision: true,
			decisionLabel: 'Confirm you want to begin the corporate dissolution process',
			helpText: 'This will start the process of closing your corporation and related accounts',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'FILE_FINAL_TAX_RETURN',
			label: 'File Final Tax Return',
			phase: 'I',
			dependsOn: ['INITIATE_OFFBOARDING'],
			outputs: ['final_tax_return_filed'],
			helpText: 'Final corporate tax return (T2) will be prepared and filed',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'CLOSE_GST_ACCOUNT',
			label: 'Close GST Account',
			phase: 'II',
			dependsOn: ['FILE_FINAL_TAX_RETURN'],
			outputs: ['gst_account_closed'],
			actionUrl: 'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/gst-hst-account/close-account.html',
			actionUrlLabel: 'Close GST Account',
			helpText: 'Close the GST/HST account with CRA',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'FILE_ARTICLES_OF_DISSOLUTION',
			label: 'File Articles of Dissolution',
			phase: 'II',
			dependsOn: ['CLOSE_GST_ACCOUNT'],
			outputs: ['dissolution_filed'],
			actionUrl: 'https://companiesoffice.gov.mb.ca/forms_mbcorporations.html',
			actionUrlLabel: 'File Dissolution Documents',
			helpText: 'File the Articles of Dissolution with the Companies Office',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UPLOAD_DISSOLUTION_CERTIFICATE',
			label: 'Upload Dissolution Certificate',
			phase: 'II',
			dependsOn: ['FILE_ARTICLES_OF_DISSOLUTION'],
			outputs: ['dissolution_certificate_uploaded'],
			requiresFiles: true,
			fileTypes: ['PDF'],
			uploadButtonLabel: 'Upload Certificate',
			helpText: 'Upload the Certificate of Dissolution from Companies Office',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'CLOSE_BANK_ACCOUNT',
			label: 'Close Bank Account',
			phase: 'II',
			dependsOn: ['UPLOAD_DISSOLUTION_CERTIFICATE'],
			outputs: ['bank_account_closed'],
			isDecision: true,
			decisionLabel: 'Confirm you have closed your business bank account',
			helpText: 'Close your business bank account and transfer any remaining funds',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'DEAUTHORIZE_THR_CORPORATE',
			label: 'Deauthorize THR (Corporate)',
			phase: 'III',
			dependsOn: ['CLOSE_BANK_ACCOUNT'],
			outputs: ['thr_corporate_deauthorized'],
			actionUrl: 'https://www.canada.ca/en/revenue-agency/services/e-services/represent-a-client.html',
			actionUrlLabel: 'Remove Representative (CRA My Business Account)',
			helpText: 'Remove THR authorization from your CRA My Business Account',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'DEAUTHORIZE_THR_PERSONAL',
			label: 'Deauthorize THR (Personal)',
			phase: 'III',
			dependsOn: ['DEAUTHORIZE_THR_CORPORATE'],
			outputs: ['thr_personal_deauthorized'],
			actionUrl: 'https://www.canada.ca/en/revenue-agency/services/e-services/represent-a-client.html',
			actionUrlLabel: 'Remove Representative (CRA My Account)',
			helpText: 'Remove THR authorization from your personal CRA My Account',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'FINAL_DOCUMENT_HANDOFF',
			label: 'Final Document Handoff',
			phase: 'III',
			dependsOn: ['DEAUTHORIZE_THR_PERSONAL'],
			outputs: ['offboarding_complete'],
			helpText: 'All corporate documents will be provided for your records',
			assignedTo: TaskUserType.Workstation,
		},
	],
};
