import type {TaskConfig} from '../types';
import {TaskUserType} from '../types';
import {DocumentTypes} from './DocumentTypes';

export const onboardingConfig: TaskConfig = {
	id: 'onboarding',
	title: 'Onboarding',
	completionMessage: 'Your onboarding is complete!',
	phases: {
		I: 'Getting Started',
		II: 'Setup & Registration',
		III: 'Final Steps',
	},
	steps: [
		{
			id: 'UploadDriversLicense',
			label: "Upload Driver's License",
			phase: 'I',
			dependsOn: [],
			outputs: ['driver_license'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Drivers License'],
			fileTypes: ['PDF', 'JPG', 'PNG'],
			uploadButtonLabel: "Upload Driver's License",
			helpText: "Please upload a clear photo of your driver's license (front and back)",
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'NameReservationDecision',
			label: 'Name Reservation Decision',
			phase: 'I',
			dependsOn: ['UploadDriversLicense'],
			outputs: ['name_reservation_required'],
			isDecision: true,
			decisionLabel: 'Do you need to reserve a specific company name before incorporation?',
			helpText: 'If you want to reserve a specific company name before incorporation, select Yes',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'FileNameReservation',
			label: 'File Name Reservation',
			phase: 'I',
			dependsOn: ['NameReservationDecision'],
			conditional: 'name_reservation_required',
			outputs: ['name_reservation_filed'],
			actionUrl: 'https://companiesoffice.gov.mb.ca/name_reservations.html',
			actionUrlLabel: 'File Name Reservation',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadNameReservationConfirmation',
			label: 'Upload Name Reservation Confirmation',
			phase: 'I',
			dependsOn: ['FileNameReservation'],
			conditional: 'name_reservation_required',
			outputs: ['name_reservation_confirmation_uploaded'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Name Reservation'],
			fileTypes: ['PDF'],
			helpText: 'Upload the Name Reservation Confirmation from Companies Office',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'FileIncorporation',
			label: 'File Incorporation Documents',
			phase: 'I',
			dependsOn: ['UploadDriversLicense'],
			outputs: ['incorporation_filed'],
			actionUrl: 'https://companiesoffice.gov.mb.ca/forms_mbcorporations.html',
			actionUrlLabel: 'File Incorporation Documents',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadArticlesOfIncorporation',
			label: 'Upload Articles of Incorporation',
			phase: 'II',
			dependsOn: ['FileIncorporation'],
			outputs: ['documents_uploaded_to_mymc'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Articles of Incorporation'],
			fileTypes: ['PDF'],
			helpText: 'Upload Articles of Incorporation',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadBusinessNumberSummary',
			label: 'Upload Business Number Summary',
			phase: 'II',
			dependsOn: ['FileIncorporation'],
			outputs: ['documents_uploaded_to_mymc'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Business Number Summary'],
			fileTypes: ['PDF'],
			helpText: 'Upload the Business Number Summary Document',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'CRA_AccessDecision',
			label: 'CRA Business Account Access Decision',
			phase: 'II',
			dependsOn: ['UploadBusinessNumberSummary'],
			outputs: ['cra_access_method'],
			isDecision: true,
			decisionLabel: 'Do you need assistance setting up your CRA My Business Account access?',
			helpText: 'If you have not set up your CRA My Business Account, select Yes.',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'AuthorizeThrPersonal',
			label: 'Authorize THR on Personal CRA Account',
			phase: 'II',
			dependsOn: ['CRA_AccessDecision'],
			outputs: ['thr_personal_authorized'],
			actionUrl: 'https://www.canada.ca/en/revenue-agency/services/e-services/represent-a-client.html',
			actionUrlLabel: 'Authorize Representative (CRA My Account)',
			helpText: 'Log into your CRA My Account to authorize THR for your personal tax file (T1).',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'AuthorizeThrCorporate',
			label: 'Authorize THR on Corporate CRA Account',
			phase: 'II',
			dependsOn: ['AuthorizeThrPersonal'],
			outputs: ['thr_corporate_authorized'],
			actionUrl: 'https://www.canada.ca/en/revenue-agency/services/e-services/represent-a-client.html',
			actionUrlLabel: 'Authorize Representative (CRA My Business Account)',
			helpText: 'Log into your CRA My Business Account to authorize THR for corporate tax files.',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'UploadByLaws',
			label: 'Upload By Laws',
			phase: 'II',
			dependsOn: ['FileIncorporation'],
			outputs: ['documents_uploaded_to_mymc'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['By Laws'],
			fileTypes: ['PDF'],
			helpText: 'Upload the By Laws',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadCertificateOfShares',
			label: 'Upload Certificate of Shares',
			phase: 'II',
			dependsOn: ['FileIncorporation'],
			outputs: ['documents_uploaded_to_mymc'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Certificate of Shares'],
			fileTypes: ['PDF'],
			helpText: 'Upload the Certificate of Shares',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadDirectorsRegister',
			label: 'Upload Directors Register',
			phase: 'II',
			dependsOn: ['FileIncorporation'],
			outputs: ['documents_uploaded_to_mymc'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Directors Register'],
			fileTypes: ['PDF'],
			helpText: 'Upload the Directors Register',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadShareholdersRegister',
			label: 'Upload Shareholders Register',
			phase: 'II',
			dependsOn: ['FileIncorporation'],
			outputs: ['documents_uploaded_to_mymc'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Shareholders Register'],
			fileTypes: ['PDF'],
			helpText: 'Upload the Shareholders Register',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'BankAccountSetupConfirmation',
			label: 'Bank Account Setup Confirmation',
			phase: 'II',
			dependsOn: ['UploadArticlesOfIncorporation'],
			outputs: ['bank_account_confirmed'],
			isDecision: true,
			decisionLabel: 'Have you completed setting up your business bank account?',
			helpText: "Please confirm once you've opened a business bank account",
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'ScheduleOnboardingMeeting',
			label: 'Schedule Onboarding Meeting',
			phase: 'II',
			dependsOn: ['BankAccountSetupConfirmation'],
			conditional: 'bank_account_confirmed',
			outputs: ['meeting_scheduled'],
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'OpenGSTAccount',
			label: 'Open GST Account',
			phase: 'II',
			dependsOn: ['UploadArticlesOfIncorporation'],
			outputs: ['gst_account_opened'],
			actionUrl: 'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/gst-hst-account/register-account.html',
			actionUrlLabel: 'Register GST Account',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'UploadVoidCheque',
			label: 'Upload Void Cheque',
			phase: 'II',
			dependsOn: ['UploadArticlesOfIncorporation'],
			outputs: ['void_cheque_created'],
			requiresFiles: true,
			fileTypeId: DocumentTypes['Void Cheque'],
			fileTypes: ['PDF', 'JPG', 'PNG'],
			helpText: 'Upload a void cheque or bank account details form',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'UploadServiceAgreement',
			label: 'Upload Service Agreement Template',
			phase: 'II',
			dependsOn: ['UploadVoidCheque'],
			outputs: ['service_agreement_uploaded'],
			requiresFiles: true,
			fileTypes: ['PDF'],
			helpText: 'Upload the completed and signed service agreement for client review',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'SignServiceAgreement',
			label: 'Sign Service Agreement',
			phase: 'II',
			dependsOn: ['UploadServiceAgreement'],
			outputs: ['service_agreement_signed'],
			helpText: 'Review and sign the service agreement',
			assignedTo: TaskUserType.Client,
		},
		{
			id: 'SetUpSalaryAndPayroll',
			label: 'Set Up Salary & Payroll',
			phase: 'III',
			dependsOn: ['SignServiceAgreement'],
			outputs: ['salary_amount_set'],
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'SetUpAccountingFees',
			label: 'Set Up Accounting Fees',
			phase: 'III',
			dependsOn: ['SetUpSalaryAndPayroll'],
			outputs: ['accounting_fees_set'],
			helpText: 'Configure accounting fees for the client account',
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'FinalizeContractsAndPayment',
			label: 'Finalize Contracts & Payment',
			phase: 'III',
			dependsOn: ['SetUpAccountingFees'],
			outputs: ['active_contract_created'],
			assignedTo: TaskUserType.Workstation,
		},
		{
			id: 'CloseHistoricalMode',
			label: 'Close Historical Mode',
			phase: 'III',
			dependsOn: ['FinalizeContractsAndPayment'],
			outputs: ['historical_mode_closed'],
			helpText: 'Close historical mode in the accounting system to prevent backdated entries',
			assignedTo: TaskUserType.System,
		},
		{
			id: 'OpenJournalEntry',
			label: 'Open Journal Entry',
			phase: 'III',
			dependsOn: ['CloseHistoricalMode'],
			outputs: ['journal_entry_opened'],
			helpText: 'Create the opening journal entry to initialize the general ledger with starting balances',
			assignedTo: TaskUserType.System,
		},
	],
};
