name: 'Check typescript'
description: 'Checks typescript'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: node_modules cache
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Run ts
      shell: bash
      run: |
        yarn ts -v

    - name: Store ts artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ts
        retention-days: 1
        path: |
          **/dist
          !node_modules/**
