name: Test Workflow
on:
  push:
    branches-ignore:
      - master

jobs:
  installdeps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 16.13
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn global add lerna
          yarn lerna bootstrap

      - name: Check dependencies
        run: |
          yarn deps -v

  lint:
    needs: installdeps
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 16.13
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

      - name: Run linting
        run: |
          yarn lint -v

  build:
    needs: installdeps
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 16.13
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

      - name: Run build
        run: |
          yarn build -v

  tests:
    needs: installdeps
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 16.13
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

      - name: Run tests
        run: |
          yarn test -v

  typescript:
    needs: installdeps
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 16.13
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

      - name: Run typescript
        run: |
          yarn ts -v
