name: Test Workflow
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 16.13
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn global add lerna
          yarn lerna bootstrap

      - name: Run linting
        run: |
          yarn lint -v

      - name: Run build
        run: |
          yarn build -v

      - name: Run tests
        run: |
          yarn test -v

      - name: Run typescript
        run: |
          yarn ts -v
